name: GeoCN Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set registry environment variable
        run: echo "REGISTRY=ghcr.io" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Geoip2
        working-directory: docker
        run: |
          chmod +x geoip2_sync.sh && ./geoip2_sync.sh
        env:
          LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: docker
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
